
- name: fetch node setup script
  shell: "curl -sL https://deb.nodesource.com/setup_6.x | bash - && touch /tmp/node-setup"
  sudo: yes
  args:
    creates: /tmp/node-setup

- name: Add erlang solutions gpg key
  apt_key: url=https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc state=present

- name: Add erlang solutions repo
  apt_repository: repo='deb http://packages.erlang-solutions.com/ubuntu xenial contrib' state=present


- name: Install web app packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - nodejs
    - erlang
    - elixir
    - postgresql-client-common

- name: Install "elm" node.js package globally.
  npm: name=elm global=yes

- name: dotenv config file
  template: src=files/web_dev.dotenv
          dest=/home/ubuntu/.env
          owner={{ansible_ssh_user}}
          mode=0644

- name: install hex
  shell: "mix local.hex --force && mix local.rebar --force"

- name: build deps
  shell: "mix deps.get && mix deps.compile"
  args:
    chdir: /vagrant/src/dguweb

- name: build deps
  shell: "npm install"
  args:
    chdir: /vagrant/src/dguweb


- name: create and migrate db
  shell: "mix ecto.create && mix ecto.migrate"
  args:
    chdir: /vagrant/src/dguweb

- name: install elm brunch
  shell: "npm install --save-dev elm-brunch"
  args:
    chdir: /vagrant/src/dguweb

- name: Fetch elm deps
  shell: "elm package install -y elm-lang/html"
  args:
    chdir: /vagrant/src/dguweb/web/elm

