- name: set timezone to Europe/London
  template: src=files/timezone dest=/etc/timezone owner=root group=root mode=0644
  sudo: yes

- name: Install Database Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - postgresql-9.5
    - postgresql-9.5-postgis-2.2
    - postgresql-server-dev-9.5
    - postgresql-client-common
    - python-psycopg2

- name: ensure template_postgis database exists
  sudo_user: postgres
  postgresql_db: name=template_postgis state=present
  register: createdb_template_postgis

- name: make template_postgis a template
  sudo_user: postgres
  command: psql -d template_postgis -c "UPDATE pg_database SET datistemplate=true WHERE datname='template_postgis';"
  when: createdb_template_postgis.changed

- name: enable postgis extension
  sudo_user: postgres
  command: psql -d template_postgis -c "CREATE EXTENSION postgis;"
  when: createdb_template_postgis.changed

- name: Create database user
  sudo: true
  sudo_user: postgres
  postgresql_user: >
    user=dgu
    password=pass
    role_attr_flags=CREATEDB,NOSUPERUSER

- name: Create the database
  postgresql_db: name=dguweb_dev
               encoding='UTF-8'
               template='template_postgis'
               owner=dgu
  sudo_user: postgres

- name: Create the test database
  postgresql_db: name=dguweb_test
               encoding='UTF-8'
               template='template_postgis'
               owner=dgu
  sudo_user: postgres

- name: Make Postgres listen for external connections
  lineinfile: dest=/etc/postgresql/9.5/main/postgresql.conf
              regexp="^listen_addresses"
              line="listen_addresses = '*' " state=present
  notify:
  - restart Postgres

- name: Allow web hosts to connect to Postgres
  template: src=files/pg_hba.conf dest=/etc/postgresql/9.5/main/pg_hba.conf owner=root group=root mode=0644
  notify:
  - restart Postgres

- name: Increase Postgres shared buffer size
  lineinfile: dest=/etc/postgresql/9.5/main/postgresql.conf regexp="^shared_buffers" line="shared_buffers = 1536MB"
  notify:
  - restart Postgres

